# Generated by Django 5.1 on 2024-09-15 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_stockentry_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="time",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
